FROM continuumio/miniconda3:main


# Set environment variables to non-interactive mode and disable conda's auto-activation
ENV CONDA_AUTO_UPDATE_CONDA=false
ENV CONDA_INSTALL_PACKAGES=""

# Set the default shell to bash
SHELL ["/bin/bash", "--login", "-c"]

WORKDIR /lab

COPY rnaseqconda.yml .

RUN conda env update -n root -f rnaseqconda.yml \
    && conda clean -a

RUN pip3 install RSeQC==3.0.1
RUN pip3 install pandas

# Start a bash shell by default
CMD ["bash"]





