name: Test Pipeline
on:
  push: 
    branches: 
      - dev

env:
  NXF_ANSI_LOG: false

jobs:
  test:
    name: testing pipeline self-hosted runner
    runs-on: [self-hosted, linux, x64]
    strategy:
      matrix:
        NXF_VER: [23.10.0]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Nextflow
      uses: nf-core/setup-nextflow@v1
      with:
        version: ${{ matrix.NXF_VER }}

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.13.1'

    - name: Install Singularity
      uses: eWaterCycle/setup-singularity@v7
      with:
       singularity-version: 3.8.3
    
    - name: Download nf-test executable script
      run: curl -fsSL https://code.askimed.com/install/nf-test | bash -s 0.8.1

    - name: Test pipeline
      run: ./nf-test test workflow-tests/main.nf.test 
    

    